[package]
name = "workshop2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
hex = "0.4"
rand = "0.8.5"
secp256k1 = "0.30.0"